name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  # push_docker:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Set up JDK
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '21'
  #         distribution: 'adopt'
  #         cache: maven
  #     - name: Compile
  #       run: mvn -B clean package
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2.2.0
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         logout: false
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: true
  #         tags: alexchenqr/inspirational-bot:latest
  push_vultr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Compile
        run: mvn -B clean package
      - name: 将 JAR 包部署到服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/InspirationalBot-1.0-SNAPSHOT.jar
          remote: InspirationalBot/jar/github-actions-springboot.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}