name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Compile
        run: mvn -B clean package --file pom.xml
      - name: JAR包部署到服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/InspirationalBot-1.0-SNAPSHOT.jar
          remote: InspirationalBot/jar/InspirationalBot-1.0-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: 在服务器启动
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 20s
          script: |
            cd InspirationalBot/jar/
            ps -ef | grep InspirationalBot-1.0-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9 
            nohup java -DbotToken="${{ secrets.BOT_TOKEN }}" -DbotUserName="${{ secrets.BOT_USERNAME }} -jar InspirationalBot-1.0-SNAPSHOT.jar" > nohup.out &
            exit